# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run script
        run: |
          pip install PyGithub
          python main.py ${{ secrets.RECORRENTE_TOKEN }}
          
      - name: Commit files
        run: |
          git config --local user.email "andrecorreia@pm.me"
          git config --local user.name "Andre Correia"
          git add .
          git commit -m "ci: gather new day" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
